### ISSUE TITLE
Set up semantic-release bot

### ISSUE THREAD

**Issue by feross** [webtorrent/node-bencode#100]
We use `semantic-release` to automatically do releases based on commit messages (`fix:`, `feat:`, etc.)

Can you set it up on this repo for us, @DiegoRBaquero?

**Comment by DiegoRBaquero** [comment]
Sure! Just to confirm, has it been moved to webtorrent npm org too?

**Comment by themasch** [comment]
The webtorrent team should have access yes, not sure there is more to the "org/team" thing than that.

**Comment by DiegoRBaquero** [comment]
Done :)

**Comment by DiegoRBaquero** [comment]
Seems old tags didn't use `v` prefix. Need to figure out how to tell it there's a v2.0.0

**Comment by DiegoRBaquero** [comment]
Fixed, cleaned up

**Comment by feross** [comment]
Thanks @DiegoRBaquero!
